name: ubunturdp
on: 
  workflow_dispatch:
   inputs:
     auth:
        description: 'GRDP Authorization Code'
        required: false
        default: 'paste your code here'
  
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: localtunnel
      run: |
         npm install -g localtunnel
    - name: webproxy & Tunneling
      run: |
          git clone https://github.com/FogNetwork/Tsunami && cd Tsunami && npm install && npx localtunnel --port 8080 && npm start
    
