name: webProxy
on: 
  workflow_dispatch:
   inputs:
     auth:
        description: 'GRDP Authorization Code'
        required: false
        default: 'paste your code here'
  
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: localtunnel
      run: |
         npm install -g localtunnel 
    - name: webproxy 
      run: |
          git clone https://github.com/FogNetwork/Tsunami && cd Tsunami && npm install
    - name: running host
      run: |
         npm start > /dev/null &
    - name: url
      run: |
        npx localtunnel --port 8080
